[package]
name = "toktok"
version = "0.1.0"
authors = ["Jannik Obermann <jannik.obermann@gmail.com>"]
edition = "2021"
rust-version = "1.56"
publish = false

[dependencies]
pretty-error = { path = "../pretty-error" } # TODO: feature flag
either = "1.6.1" # TODO: feature flag (default)
