[book]
authors = ["Jannik Obermann"]
language = "en"
multilingual = false
src = "src"
title = "RTeasy-Online"

[output.html]
site-url = "/rteasy-online/book/"
additional-css = ["theme/custom.css"]

[output.html.code.hidelines]
rteasy = "~"

[build]
build-dir = "build"
